# Generated by Django 4.0.4 on 2022-04-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=500)),
            ],
        ),
    ]
