# Generated by Django 4.0.4 on 2022-04-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heme_app', '0002_alter_login_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
