# Generated by Django 4.0.4 on 2022-04-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heme_app', '0003_alter_login_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
