# Generated by Django 4.0.4 on 2022-04-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heme_app', '0004_login_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='view',
            field=models.DateField(null=True),
        ),
    ]
