# Generated by Django 4.0.4 on 2022-05-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heme_app', '0005_login_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
