# Generated by Django 4.0.4 on 2022-05-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heme_app', '0006_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='body',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='topic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
