# Generated by Django 4.0.5 on 2022-06-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heme_app', '0009_remove_login_time_remove_login_view_login_view_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='User',
        ),
    ]
