# Generated by Django 4.0.5 on 2022-07-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heme_app', '0010_rename_login_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='file',
        ),
    ]
