# Generated by Django 4.0 on 2022-10-30 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='نام')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='ایمیل')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='موضوع')),
                ('body', models.TextField(blank=True, max_length=5000, verbose_name='پیام')),
                ('view_Time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر ها',
            },
        ),
    ]
