# Generated by Django 4.0 on 2022-10-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
