# Generated by Django 4.0 on 2022-10-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='body',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, default=3, max_length=100),
            preserve_default=False,
        ),
    ]
