# Generated by Django 4.0 on 2022-10-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='موضوع'),
        ),
    ]
