# Generated by Django 4.0 on 2022-10-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_user_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
        migrations.AddField(
            model_name='user',
            name='topic',
            field=models.CharField(default=4, max_length=80, verbose_name='موضوع'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=90, verbose_name='نام'),
        ),
    ]
