# Generated by Django 4.0 on 2022-11-01 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_comment_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
