# Generated by Django 4.2.2 on 2023-07-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=500, verbose_name='instagram')),
                ('linkedin', models.CharField(max_length=500, verbose_name='linkedin')),
                ('github', models.CharField(max_length=500, verbose_name='github')),
                ('telegram', models.CharField(max_length=500, verbose_name='telegram')),
            ],
            options={
                'verbose_name': 'شبکه های من',
                'verbose_name_plural': 'شبکه های من',
            },
        ),
    ]
