# Generated by Django 4.2.2 on 2023-07-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_mysocialnetworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysocialnetworks',
            name='github',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='github'),
        ),
        migrations.AlterField(
            model_name='mysocialnetworks',
            name='instagram',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='mysocialnetworks',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='linkedin'),
        ),
        migrations.AlterField(
            model_name='mysocialnetworks',
            name='telegram',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='telegram'),
        ),
    ]
