# Generated by Django 4.2.2 on 2023-08-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Services', verbose_name='image')),
                ('title', models.CharField(max_length=90, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'خدمات',
                'verbose_name_plural': 'سروریس',
            },
        ),
        migrations.AlterModelOptions(
            name='cv',
            options={'verbose_name': 'درباره من', 'verbose_name_plural': 'درباره من'},
        ),
    ]
