# Generated by Django 4.2.2 on 2023-08-22 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_services_alter_cv_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='time_ser',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
