# Generated by Django 4.2.2 on 2023-08-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_services_time_ser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='پلن')),
                ('subject', models.TextField(verbose_name='موضوع')),
                ('support', models.CharField(max_length=90, verbose_name='پشتیبانی')),
                ('price', models.CharField(max_length=90, verbose_name='قیمت')),
                ('days', models.CharField(max_length=40, verbose_name='پلن چند روزه')),
                ('proposal', models.BooleanField(blank=True, default=False, null=True, verbose_name='پیشنهاد')),
            ],
            options={
                'verbose_name': 'پلن',
                'verbose_name_plural': 'پلن قیمت',
            },
        ),
    ]
